// Copyright 2024 Alexey Lavrenchenko. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package headers

const (
	HeaderNameAccept                          = "Accept"
	HeaderNameAcceptCharset                   = "Accept-Charset"
	HeaderNameAcceptEncoding                  = "Accept-Encoding"
	HeaderNameAcceptLanguage                  = "Accept-Language"
	HeaderNameAcceptRanges                    = "Accept-Ranges"
	HeaderNameAccessControlAllowCredentials   = "Access-Control-Allow-Credentials"
	HeaderNameAccessControlAllowHeaders       = "Access-Control-Allow-Headers"
	HeaderNameAccessControlAllowMethods       = "Access-Control-Allow-Methods"
	HeaderNameAccessControlAllowOrigin        = "Access-Control-Allow-Origin"
	HeaderNameAccessControlExposeHeaders      = "Access-Control-Expose-Headers"
	HeaderNameAccessControlMaxAge             = "Access-Control-Max-Age"
	HeaderNameAccessControlRequestHeaders     = "Access-Control-Request-Headers"
	HeaderNameAccessControlRequestMethod      = "Access-Control-Request-Method"
	HeaderNameAge                             = "Age"
	HeaderNameAllow                           = "Allow"
	HeaderNameAltSvc                          = "Alt-Svc"
	HeaderNameAuthority                       = ":authority"
	HeaderNameAuthorization                   = "Authorization"
	HeaderNameCacheControl                    = "Cache-Control"
	HeaderNameConnection                      = "Connection"
	HeaderNameContentDisposition              = "Content-Disposition"
	HeaderNameContentEncoding                 = "Content-Encoding"
	HeaderNameContentLanguage                 = "Content-Language"
	HeaderNameContentLength                   = "Content-Length"
	HeaderNameContentLocation                 = "Content-Location"
	HeaderNameContentMD5                      = "Content-MD5"
	HeaderNameContentRange                    = "Content-Range"
	HeaderNameContentSecurityPolicy           = "Content-Security-Policy"
	HeaderNameContentSecurityPolicyReportOnly = "Content-Security-Policy-Report-Only"
	HeaderNameContentType                     = "Content-Type"
	HeaderNameCorrelationContext              = "Correlation-Context"
	HeaderNameCookie                          = "Cookie"
	HeaderNameDate                            = "Date"
	HeaderNameETag                            = "ETag"
	HeaderNameExpires                         = "Expires"
	HeaderNameExpect                          = "Expect"
	HeaderNameFrom                            = "From"
	HeaderNameGrpcAcceptEncoding              = "Grpc-Accept-Encoding"
	HeaderNameGrpcEncoding                    = "Grpc-Encoding"
	HeaderNameGrpcMessage                     = "Grpc-Message"
	HeaderNameGrpcStatus                      = "Grpc-Status"
	HeaderNameGrpcTimeout                     = "Grpc-Timeout"
	HeaderNameHost                            = "Host"
	HeaderNameKeepAlive                       = "Keep-Alive"
	HeaderNameIfMatch                         = "If-Match"
	HeaderNameIfModifiedSince                 = "If-Modified-Since"
	HeaderNameIfNoneMatch                     = "If-None-Match"
	HeaderNameIfRange                         = "If-Range"
	HeaderNameIfUnmodifiedSince               = "If-Unmodified-Since"
	HeaderNameLastModified                    = "Last-Modified"
	HeaderNameLink                            = "Link"
	HeaderNameLocation                        = "Location"
	HeaderNameMaxForwards                     = "Max-Forwards"
	HeaderNameMethod                          = ":method"
	HeaderNameOrigin                          = "Origin"
	HeaderNamePath                            = ":path"
	HeaderNamePragma                          = "Pragma"
	HeaderNameProxyAuthenticate               = "Proxy-Authenticate"
	HeaderNameProxyAuthorization              = "Proxy-Authorization"
	HeaderNameProxyConnection                 = "Proxy-Connection"
	HeaderNameRange                           = "Range"
	HeaderNameReferer                         = "Referer"
	HeaderNameRetryAfter                      = "Retry-After"
	HeaderNameRequestId                       = "Request-Id"
	HeaderNameScheme                          = ":scheme"
	HeaderNameSecWebSocketAccept              = "Sec-WebSocket-Accept"
	HeaderNameSecWebSocketKey                 = "Sec-WebSocket-Key"
	HeaderNameSecWebSocketProtocol            = "Sec-WebSocket-Protocol"
	HeaderNameSecWebSocketVersion             = "Sec-WebSocket-Version"
	HeaderNameSecWebSocketExtensions          = "Sec-WebSocket-Extensions"
	HeaderNameServer                          = "Server"
	HeaderNameSetCookie                       = "Set-Cookie"
	HeaderNameStatus                          = ":status"
	HeaderNameStrictTransportSecurity         = "Strict-Transport-Security"
	HeaderNameTE                              = "TE"
	HeaderNameTrailer                         = "Trailer"
	HeaderNameTransferEncoding                = "Transfer-Encoding"
	HeaderNameTranslate                       = "Translate"
	HeaderNameTraceParent                     = "traceparent"
	HeaderNameTraceState                      = "tracestate"
	HeaderNameUpgrade                         = "Upgrade"
	HeaderNameUpgradeInsecureRequests         = "Upgrade-Insecure-Requests"
	HeaderNameUserAgent                       = "User-Agent"
	HeaderNameVary                            = "Vary"
	HeaderNameVia                             = "Via"
	HeaderNameWarning                         = "Warning"
	HeaderNameWebSocketSubProtocols           = "Sec-WebSocket-Protocol"
	HeaderNameWWWAuthenticate                 = "WWW-Authenticate"
	HeaderNameXContentTypeOptions             = "X-Content-Type-Options"
	HeaderNameXFrameOptions                   = "X-Frame-Options"
	HeaderNameXPoweredBy                      = "X-Powered-By"
	HeaderNameXRequestedWith                  = "X-Requested-With"
	HeaderNameXUACompatible                   = "X-UA-Compatible"
	HeaderNameXXSSProtection                  = "X-XSS-Protection"
)
