// Copyright 2023 Alexey Lavrenchenko. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: apis/identity/permissions/groups/permission_group.proto

package groups

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The permission group status.
type PermissionGroupStatusEnum_PermissionGroupStatus int32

const (
	// Unspecified. Do not use.
	PermissionGroupStatusEnum_UNSPECIFIED PermissionGroupStatusEnum_PermissionGroupStatus = 0
	PermissionGroupStatusEnum_NEW         PermissionGroupStatusEnum_PermissionGroupStatus = 1
	PermissionGroupStatusEnum_ACTIVE      PermissionGroupStatusEnum_PermissionGroupStatus = 2
	PermissionGroupStatusEnum_INACTIVE    PermissionGroupStatusEnum_PermissionGroupStatus = 3
	PermissionGroupStatusEnum_DELETING    PermissionGroupStatusEnum_PermissionGroupStatus = 4
	PermissionGroupStatusEnum_DELETED     PermissionGroupStatusEnum_PermissionGroupStatus = 5
)

// Enum value maps for PermissionGroupStatusEnum_PermissionGroupStatus.
var (
	PermissionGroupStatusEnum_PermissionGroupStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NEW",
		2: "ACTIVE",
		3: "INACTIVE",
		4: "DELETING",
		5: "DELETED",
	}
	PermissionGroupStatusEnum_PermissionGroupStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"NEW":         1,
		"ACTIVE":      2,
		"INACTIVE":    3,
		"DELETING":    4,
		"DELETED":     5,
	}
)

func (x PermissionGroupStatusEnum_PermissionGroupStatus) Enum() *PermissionGroupStatusEnum_PermissionGroupStatus {
	p := new(PermissionGroupStatusEnum_PermissionGroupStatus)
	*p = x
	return p
}

func (x PermissionGroupStatusEnum_PermissionGroupStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionGroupStatusEnum_PermissionGroupStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_apis_identity_permissions_groups_permission_group_proto_enumTypes[0].Descriptor()
}

func (PermissionGroupStatusEnum_PermissionGroupStatus) Type() protoreflect.EnumType {
	return &file_apis_identity_permissions_groups_permission_group_proto_enumTypes[0]
}

func (x PermissionGroupStatusEnum_PermissionGroupStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionGroupStatusEnum_PermissionGroupStatus.Descriptor instead.
func (PermissionGroupStatusEnum_PermissionGroupStatus) EnumDescriptor() ([]byte, []int) {
	return file_apis_identity_permissions_groups_permission_group_proto_rawDescGZIP(), []int{1, 0}
}

// The permission group.
type PermissionGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique ID to identify the permission group.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The unique name to identify the permission group.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// It stores the date and time at which the permission group was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The user ID to identify the user who created the permission group.
	CreatedBy uint64 `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// It stores the date and time at which the permission group was updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The user ID to identify the user who updated the permission group.
	UpdatedBy uint64 `protobuf:"varint,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// The permission group status.
	Status PermissionGroupStatusEnum_PermissionGroupStatus `protobuf:"varint,7,opt,name=status,proto3,enum=personalwebsite.identity.permissions.groups.PermissionGroupStatusEnum_PermissionGroupStatus" json:"status,omitempty"`
	// It stores the date and time at which the permission group status was updated.
	StatusUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=status_updated_at,json=statusUpdatedAt,proto3" json:"status_updated_at,omitempty"`
	// The user ID to identify the user who updated the permission group status.
	StatusUpdatedBy uint64 `protobuf:"varint,9,opt,name=status_updated_by,json=statusUpdatedBy,proto3" json:"status_updated_by,omitempty"`
	// Optional. The permission group status comment.
	StatusComment *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=status_comment,json=statusComment,proto3" json:"status_comment,omitempty"`
	// Optional. The app ID.
	AppId *wrapperspb.UInt64Value `protobuf:"bytes,11,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Optional. The app group ID.
	AppGroupId *wrapperspb.UInt64Value `protobuf:"bytes,12,opt,name=app_group_id,json=appGroupId,proto3" json:"app_group_id,omitempty"`
	// The permission group description.
	Description string `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *PermissionGroup) Reset() {
	*x = PermissionGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_identity_permissions_groups_permission_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionGroup) ProtoMessage() {}

func (x *PermissionGroup) ProtoReflect() protoreflect.Message {
	mi := &file_apis_identity_permissions_groups_permission_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionGroup.ProtoReflect.Descriptor instead.
func (*PermissionGroup) Descriptor() ([]byte, []int) {
	return file_apis_identity_permissions_groups_permission_group_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionGroup) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionGroup) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PermissionGroup) GetCreatedBy() uint64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *PermissionGroup) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PermissionGroup) GetUpdatedBy() uint64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *PermissionGroup) GetStatus() PermissionGroupStatusEnum_PermissionGroupStatus {
	if x != nil {
		return x.Status
	}
	return PermissionGroupStatusEnum_UNSPECIFIED
}

func (x *PermissionGroup) GetStatusUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusUpdatedAt
	}
	return nil
}

func (x *PermissionGroup) GetStatusUpdatedBy() uint64 {
	if x != nil {
		return x.StatusUpdatedBy
	}
	return 0
}

func (x *PermissionGroup) GetStatusComment() *wrapperspb.StringValue {
	if x != nil {
		return x.StatusComment
	}
	return nil
}

func (x *PermissionGroup) GetAppId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.AppId
	}
	return nil
}

func (x *PermissionGroup) GetAppGroupId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.AppGroupId
	}
	return nil
}

func (x *PermissionGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Container for enum describing the permission group status.
type PermissionGroupStatusEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PermissionGroupStatusEnum) Reset() {
	*x = PermissionGroupStatusEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_identity_permissions_groups_permission_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionGroupStatusEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionGroupStatusEnum) ProtoMessage() {}

func (x *PermissionGroupStatusEnum) ProtoReflect() protoreflect.Message {
	mi := &file_apis_identity_permissions_groups_permission_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionGroupStatusEnum.ProtoReflect.Descriptor instead.
func (*PermissionGroupStatusEnum) Descriptor() ([]byte, []int) {
	return file_apis_identity_permissions_groups_permission_group_proto_rawDescGZIP(), []int{1}
}

var File_apis_identity_permissions_groups_permission_group_proto protoreflect.FileDescriptor

var file_apis_identity_permissions_groups_permission_group_proto_rawDesc = []byte{
	0x0a, 0x37, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2b, 0x70, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x6c, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x05, 0x0a, 0x0f, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x62, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x42, 0x79, 0x12, 0x74, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x5c, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x77, 0x65,
	0x62, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x46, 0x0a, 0x11, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x43, 0x0a,
	0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x0c, 0x61, 0x70, 0x70, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x55, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a, 0x61, 0x70, 0x70,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x83, 0x01, 0x0a, 0x19, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x66, 0x0a, 0x15, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43,
	0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49,
	0x56, 0x45, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x49, 0x4e, 0x47,
	0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x05, 0x42,
	0x40, 0x5a, 0x3e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x2d, 0x77, 0x65, 0x62, 0x73,
	0x69, 0x74, 0x65, 0x2d, 0x76, 0x32, 0x2f, 0x67, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x3b, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_identity_permissions_groups_permission_group_proto_rawDescOnce sync.Once
	file_apis_identity_permissions_groups_permission_group_proto_rawDescData = file_apis_identity_permissions_groups_permission_group_proto_rawDesc
)

func file_apis_identity_permissions_groups_permission_group_proto_rawDescGZIP() []byte {
	file_apis_identity_permissions_groups_permission_group_proto_rawDescOnce.Do(func() {
		file_apis_identity_permissions_groups_permission_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_identity_permissions_groups_permission_group_proto_rawDescData)
	})
	return file_apis_identity_permissions_groups_permission_group_proto_rawDescData
}

var file_apis_identity_permissions_groups_permission_group_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apis_identity_permissions_groups_permission_group_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apis_identity_permissions_groups_permission_group_proto_goTypes = []interface{}{
	(PermissionGroupStatusEnum_PermissionGroupStatus)(0), // 0: personalwebsite.identity.permissions.groups.PermissionGroupStatusEnum.PermissionGroupStatus
	(*PermissionGroup)(nil),                              // 1: personalwebsite.identity.permissions.groups.PermissionGroup
	(*PermissionGroupStatusEnum)(nil),                    // 2: personalwebsite.identity.permissions.groups.PermissionGroupStatusEnum
	(*timestamppb.Timestamp)(nil),                        // 3: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),                       // 4: google.protobuf.StringValue
	(*wrapperspb.UInt64Value)(nil),                       // 5: google.protobuf.UInt64Value
}
var file_apis_identity_permissions_groups_permission_group_proto_depIdxs = []int32{
	3, // 0: personalwebsite.identity.permissions.groups.PermissionGroup.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: personalwebsite.identity.permissions.groups.PermissionGroup.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: personalwebsite.identity.permissions.groups.PermissionGroup.status:type_name -> personalwebsite.identity.permissions.groups.PermissionGroupStatusEnum.PermissionGroupStatus
	3, // 3: personalwebsite.identity.permissions.groups.PermissionGroup.status_updated_at:type_name -> google.protobuf.Timestamp
	4, // 4: personalwebsite.identity.permissions.groups.PermissionGroup.status_comment:type_name -> google.protobuf.StringValue
	5, // 5: personalwebsite.identity.permissions.groups.PermissionGroup.app_id:type_name -> google.protobuf.UInt64Value
	5, // 6: personalwebsite.identity.permissions.groups.PermissionGroup.app_group_id:type_name -> google.protobuf.UInt64Value
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_apis_identity_permissions_groups_permission_group_proto_init() }
func file_apis_identity_permissions_groups_permission_group_proto_init() {
	if File_apis_identity_permissions_groups_permission_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_identity_permissions_groups_permission_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_identity_permissions_groups_permission_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionGroupStatusEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_identity_permissions_groups_permission_group_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apis_identity_permissions_groups_permission_group_proto_goTypes,
		DependencyIndexes: file_apis_identity_permissions_groups_permission_group_proto_depIdxs,
		EnumInfos:         file_apis_identity_permissions_groups_permission_group_proto_enumTypes,
		MessageInfos:      file_apis_identity_permissions_groups_permission_group_proto_msgTypes,
	}.Build()
	File_apis_identity_permissions_groups_permission_group_proto = out.File
	file_apis_identity_permissions_groups_permission_group_proto_rawDesc = nil
	file_apis_identity_permissions_groups_permission_group_proto_goTypes = nil
	file_apis_identity_permissions_groups_permission_group_proto_depIdxs = nil
}
