// Copyright 2023 Alexey Lavrenchenko. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: apis/identity/roles/role.proto

package roles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The role type.
type RoleTypeEnum_RoleType int32

const (
	// Unspecified. Do not use.
	RoleTypeEnum_UNSPECIFIED RoleTypeEnum_RoleType = 0
	RoleTypeEnum_SYSTEM      RoleTypeEnum_RoleType = 1
	RoleTypeEnum_SERVICE     RoleTypeEnum_RoleType = 2
)

// Enum value maps for RoleTypeEnum_RoleType.
var (
	RoleTypeEnum_RoleType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SYSTEM",
		2: "SERVICE",
	}
	RoleTypeEnum_RoleType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"SYSTEM":      1,
		"SERVICE":     2,
	}
)

func (x RoleTypeEnum_RoleType) Enum() *RoleTypeEnum_RoleType {
	p := new(RoleTypeEnum_RoleType)
	*p = x
	return p
}

func (x RoleTypeEnum_RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleTypeEnum_RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_apis_identity_roles_role_proto_enumTypes[0].Descriptor()
}

func (RoleTypeEnum_RoleType) Type() protoreflect.EnumType {
	return &file_apis_identity_roles_role_proto_enumTypes[0]
}

func (x RoleTypeEnum_RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleTypeEnum_RoleType.Descriptor instead.
func (RoleTypeEnum_RoleType) EnumDescriptor() ([]byte, []int) {
	return file_apis_identity_roles_role_proto_rawDescGZIP(), []int{1, 0}
}

// The role status.
type RoleStatusEnum_RoleStatus int32

const (
	// Unspecified. Do not use.
	RoleStatusEnum_UNSPECIFIED RoleStatusEnum_RoleStatus = 0
	RoleStatusEnum_NEW         RoleStatusEnum_RoleStatus = 1
	RoleStatusEnum_ACTIVE      RoleStatusEnum_RoleStatus = 2
	RoleStatusEnum_INACTIVE    RoleStatusEnum_RoleStatus = 3
	RoleStatusEnum_DELETING    RoleStatusEnum_RoleStatus = 4
	RoleStatusEnum_DELETED     RoleStatusEnum_RoleStatus = 5
)

// Enum value maps for RoleStatusEnum_RoleStatus.
var (
	RoleStatusEnum_RoleStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NEW",
		2: "ACTIVE",
		3: "INACTIVE",
		4: "DELETING",
		5: "DELETED",
	}
	RoleStatusEnum_RoleStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"NEW":         1,
		"ACTIVE":      2,
		"INACTIVE":    3,
		"DELETING":    4,
		"DELETED":     5,
	}
)

func (x RoleStatusEnum_RoleStatus) Enum() *RoleStatusEnum_RoleStatus {
	p := new(RoleStatusEnum_RoleStatus)
	*p = x
	return p
}

func (x RoleStatusEnum_RoleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleStatusEnum_RoleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_apis_identity_roles_role_proto_enumTypes[1].Descriptor()
}

func (RoleStatusEnum_RoleStatus) Type() protoreflect.EnumType {
	return &file_apis_identity_roles_role_proto_enumTypes[1]
}

func (x RoleStatusEnum_RoleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleStatusEnum_RoleStatus.Descriptor instead.
func (RoleStatusEnum_RoleStatus) EnumDescriptor() ([]byte, []int) {
	return file_apis_identity_roles_role_proto_rawDescGZIP(), []int{2, 0}
}

// The role.
type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique ID to identify the role.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The unique name to identify the role.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The role type.
	Type RoleTypeEnum_RoleType `protobuf:"varint,3,opt,name=type,proto3,enum=personalwebsite.identity.roles.RoleTypeEnum_RoleType" json:"type,omitempty"`
	// The role title.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// It stores the date and time at which the role was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The user ID to identify the user who created the role.
	CreatedBy uint64 `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// It stores the date and time at which the role was updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The user ID to identify the user who updated the role.
	UpdatedBy uint64 `protobuf:"varint,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// The role status.
	Status RoleStatusEnum_RoleStatus `protobuf:"varint,9,opt,name=status,proto3,enum=personalwebsite.identity.roles.RoleStatusEnum_RoleStatus" json:"status,omitempty"`
	// It stores the date and time at which the role status was updated.
	StatusUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=status_updated_at,json=statusUpdatedAt,proto3" json:"status_updated_at,omitempty"`
	// The user ID to identify the user who updated the role status.
	StatusUpdatedBy uint64 `protobuf:"varint,11,opt,name=status_updated_by,json=statusUpdatedBy,proto3" json:"status_updated_by,omitempty"`
	// Optional. The role status comment.
	StatusComment *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=status_comment,json=statusComment,proto3" json:"status_comment,omitempty"`
	// Optional. The app ID.
	AppId *wrapperspb.UInt64Value `protobuf:"bytes,13,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Optional. The app group ID.
	AppGroupId *wrapperspb.UInt64Value `protobuf:"bytes,14,opt,name=app_group_id,json=appGroupId,proto3" json:"app_group_id,omitempty"`
	// The role description.
	Description string `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_identity_roles_role_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_apis_identity_roles_role_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_apis_identity_roles_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetType() RoleTypeEnum_RoleType {
	if x != nil {
		return x.Type
	}
	return RoleTypeEnum_UNSPECIFIED
}

func (x *Role) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Role) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Role) GetCreatedBy() uint64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Role) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Role) GetUpdatedBy() uint64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *Role) GetStatus() RoleStatusEnum_RoleStatus {
	if x != nil {
		return x.Status
	}
	return RoleStatusEnum_UNSPECIFIED
}

func (x *Role) GetStatusUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusUpdatedAt
	}
	return nil
}

func (x *Role) GetStatusUpdatedBy() uint64 {
	if x != nil {
		return x.StatusUpdatedBy
	}
	return 0
}

func (x *Role) GetStatusComment() *wrapperspb.StringValue {
	if x != nil {
		return x.StatusComment
	}
	return nil
}

func (x *Role) GetAppId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.AppId
	}
	return nil
}

func (x *Role) GetAppGroupId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.AppGroupId
	}
	return nil
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Container for enum describing the role type.
type RoleTypeEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleTypeEnum) Reset() {
	*x = RoleTypeEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_identity_roles_role_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleTypeEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleTypeEnum) ProtoMessage() {}

func (x *RoleTypeEnum) ProtoReflect() protoreflect.Message {
	mi := &file_apis_identity_roles_role_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleTypeEnum.ProtoReflect.Descriptor instead.
func (*RoleTypeEnum) Descriptor() ([]byte, []int) {
	return file_apis_identity_roles_role_proto_rawDescGZIP(), []int{1}
}

// Container for enum describing the role status.
type RoleStatusEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleStatusEnum) Reset() {
	*x = RoleStatusEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_identity_roles_role_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleStatusEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleStatusEnum) ProtoMessage() {}

func (x *RoleStatusEnum) ProtoReflect() protoreflect.Message {
	mi := &file_apis_identity_roles_role_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleStatusEnum.ProtoReflect.Descriptor instead.
func (*RoleStatusEnum) Descriptor() ([]byte, []int) {
	return file_apis_identity_roles_role_proto_rawDescGZIP(), []int{2}
}

var File_apis_identity_roles_role_proto protoreflect.FileDescriptor

var file_apis_identity_roles_role_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f,
	0x72, 0x6f, 0x6c, 0x65, 0x73, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74,
	0x65, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xe2, 0x05, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x49,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x35, 0x2e, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x62, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x42, 0x79, 0x12, 0x51, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x39, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x77, 0x65,
	0x62, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x72,
	0x6f, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45,
	0x6e, 0x75, 0x6d, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x46, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2a,
	0x0a, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x62, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x43, 0x0a, 0x0e, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x33, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x0c, 0x61, 0x70, 0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x44, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x34, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x02, 0x22, 0x6d, 0x0a, 0x0e,
	0x52, 0x6f, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x5b,
	0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a, 0x0b,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x4e, 0x45, 0x57, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45,
	0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x03,
	0x12, 0x0c, 0x0a, 0x08, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x0b,
	0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x05, 0x42, 0x32, 0x5a, 0x30, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x2d, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x2d,
	0x76, 0x32, 0x2f, 0x67, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x3b, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_identity_roles_role_proto_rawDescOnce sync.Once
	file_apis_identity_roles_role_proto_rawDescData = file_apis_identity_roles_role_proto_rawDesc
)

func file_apis_identity_roles_role_proto_rawDescGZIP() []byte {
	file_apis_identity_roles_role_proto_rawDescOnce.Do(func() {
		file_apis_identity_roles_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_identity_roles_role_proto_rawDescData)
	})
	return file_apis_identity_roles_role_proto_rawDescData
}

var file_apis_identity_roles_role_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_apis_identity_roles_role_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apis_identity_roles_role_proto_goTypes = []interface{}{
	(RoleTypeEnum_RoleType)(0),     // 0: personalwebsite.identity.roles.RoleTypeEnum.RoleType
	(RoleStatusEnum_RoleStatus)(0), // 1: personalwebsite.identity.roles.RoleStatusEnum.RoleStatus
	(*Role)(nil),                   // 2: personalwebsite.identity.roles.Role
	(*RoleTypeEnum)(nil),           // 3: personalwebsite.identity.roles.RoleTypeEnum
	(*RoleStatusEnum)(nil),         // 4: personalwebsite.identity.roles.RoleStatusEnum
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil), // 6: google.protobuf.StringValue
	(*wrapperspb.UInt64Value)(nil), // 7: google.protobuf.UInt64Value
}
var file_apis_identity_roles_role_proto_depIdxs = []int32{
	0, // 0: personalwebsite.identity.roles.Role.type:type_name -> personalwebsite.identity.roles.RoleTypeEnum.RoleType
	5, // 1: personalwebsite.identity.roles.Role.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: personalwebsite.identity.roles.Role.updated_at:type_name -> google.protobuf.Timestamp
	1, // 3: personalwebsite.identity.roles.Role.status:type_name -> personalwebsite.identity.roles.RoleStatusEnum.RoleStatus
	5, // 4: personalwebsite.identity.roles.Role.status_updated_at:type_name -> google.protobuf.Timestamp
	6, // 5: personalwebsite.identity.roles.Role.status_comment:type_name -> google.protobuf.StringValue
	7, // 6: personalwebsite.identity.roles.Role.app_id:type_name -> google.protobuf.UInt64Value
	7, // 7: personalwebsite.identity.roles.Role.app_group_id:type_name -> google.protobuf.UInt64Value
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_apis_identity_roles_role_proto_init() }
func file_apis_identity_roles_role_proto_init() {
	if File_apis_identity_roles_role_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_identity_roles_role_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_identity_roles_role_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleTypeEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_identity_roles_role_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleStatusEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_identity_roles_role_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apis_identity_roles_role_proto_goTypes,
		DependencyIndexes: file_apis_identity_roles_role_proto_depIdxs,
		EnumInfos:         file_apis_identity_roles_role_proto_enumTypes,
		MessageInfos:      file_apis_identity_roles_role_proto_msgTypes,
	}.Build()
	File_apis_identity_roles_role_proto = out.File
	file_apis_identity_roles_role_proto_rawDesc = nil
	file_apis_identity_roles_role_proto_goTypes = nil
	file_apis_identity_roles_role_proto_depIdxs = nil
}
