// Copyright 2023 Alexey Lavrenchenko. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: apis/identity/roles/userroleassignments/user_role_assignment_service.proto

package userroleassignments

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserRoleAssignmentService_GetById_FullMethodName                     = "/personalwebsite.identity.roles.userroleassignments.UserRoleAssignmentService/GetById"
	UserRoleAssignmentService_GetByRoleAssignmentId_FullMethodName       = "/personalwebsite.identity.roles.userroleassignments.UserRoleAssignmentService/GetByRoleAssignmentId"
	UserRoleAssignmentService_GetAllByUserId_FullMethodName              = "/personalwebsite.identity.roles.userroleassignments.UserRoleAssignmentService/GetAllByUserId"
	UserRoleAssignmentService_Exists_FullMethodName                      = "/personalwebsite.identity.roles.userroleassignments.UserRoleAssignmentService/Exists"
	UserRoleAssignmentService_IsAssigned_FullMethodName                  = "/personalwebsite.identity.roles.userroleassignments.UserRoleAssignmentService/IsAssigned"
	UserRoleAssignmentService_GetIdByRoleAssignmentId_FullMethodName     = "/personalwebsite.identity.roles.userroleassignments.UserRoleAssignmentService/GetIdByRoleAssignmentId"
	UserRoleAssignmentService_GetStatusById_FullMethodName               = "/personalwebsite.identity.roles.userroleassignments.UserRoleAssignmentService/GetStatusById"
	UserRoleAssignmentService_GetStatusByRoleAssignmentId_FullMethodName = "/personalwebsite.identity.roles.userroleassignments.UserRoleAssignmentService/GetStatusByRoleAssignmentId"
	UserRoleAssignmentService_GetUserRoleIdsByUserId_FullMethodName      = "/personalwebsite.identity.roles.userroleassignments.UserRoleAssignmentService/GetUserRoleIdsByUserId"
)

// UserRoleAssignmentServiceClient is the client API for UserRoleAssignmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRoleAssignmentServiceClient interface {
	// Gets a user's role assignment by the specified user's role assignment ID.
	GetById(ctx context.Context, in *GetByIdRequest, opts ...grpc.CallOption) (*GetByIdResponse, error)
	// Gets a user's role assignment by the specified role assignment ID.
	GetByRoleAssignmentId(ctx context.Context, in *GetByRoleAssignmentIdRequest, opts ...grpc.CallOption) (*GetByRoleAssignmentIdResponse, error)
	// Gets all user's role assignments by the specified user ID.
	GetAllByUserId(ctx context.Context, in *GetAllByUserIdRequest, opts ...grpc.CallOption) (*GetAllByUserIdResponse, error)
	// Returns true if the user's role assignment exists.
	Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error)
	// Returns true if the role is assigned to the user.
	IsAssigned(ctx context.Context, in *IsAssignedRequest, opts ...grpc.CallOption) (*IsAssignedResponse, error)
	// Gets the user's role assignment ID by the specified role assignment ID.
	GetIdByRoleAssignmentId(ctx context.Context, in *GetIdByRoleAssignmentIdRequest, opts ...grpc.CallOption) (*GetIdByRoleAssignmentIdResponse, error)
	// Gets a user's role assignment status by the specified user's role assignment ID.
	GetStatusById(ctx context.Context, in *GetStatusByIdRequest, opts ...grpc.CallOption) (*GetStatusByIdResponse, error)
	// Gets a user's role assignment status by the specified role assignment ID.
	GetStatusByRoleAssignmentId(ctx context.Context, in *GetStatusByRoleAssignmentIdRequest, opts ...grpc.CallOption) (*GetStatusByRoleAssignmentIdResponse, error)
	// Gets the IDs of the roles assigned to the user by the specified user ID.
	// If the role filter is empty, then all assigned roles are returned, otherwise only the roles
	// specified in the filter, if any, are returned.
	GetUserRoleIdsByUserId(ctx context.Context, in *GetUserRoleIdsByUserIdRequest, opts ...grpc.CallOption) (*GetUserRoleIdsByUserIdResponse, error)
}

type userRoleAssignmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRoleAssignmentServiceClient(cc grpc.ClientConnInterface) UserRoleAssignmentServiceClient {
	return &userRoleAssignmentServiceClient{cc}
}

func (c *userRoleAssignmentServiceClient) GetById(ctx context.Context, in *GetByIdRequest, opts ...grpc.CallOption) (*GetByIdResponse, error) {
	out := new(GetByIdResponse)
	err := c.cc.Invoke(ctx, UserRoleAssignmentService_GetById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleAssignmentServiceClient) GetByRoleAssignmentId(ctx context.Context, in *GetByRoleAssignmentIdRequest, opts ...grpc.CallOption) (*GetByRoleAssignmentIdResponse, error) {
	out := new(GetByRoleAssignmentIdResponse)
	err := c.cc.Invoke(ctx, UserRoleAssignmentService_GetByRoleAssignmentId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleAssignmentServiceClient) GetAllByUserId(ctx context.Context, in *GetAllByUserIdRequest, opts ...grpc.CallOption) (*GetAllByUserIdResponse, error) {
	out := new(GetAllByUserIdResponse)
	err := c.cc.Invoke(ctx, UserRoleAssignmentService_GetAllByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleAssignmentServiceClient) Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error) {
	out := new(ExistsResponse)
	err := c.cc.Invoke(ctx, UserRoleAssignmentService_Exists_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleAssignmentServiceClient) IsAssigned(ctx context.Context, in *IsAssignedRequest, opts ...grpc.CallOption) (*IsAssignedResponse, error) {
	out := new(IsAssignedResponse)
	err := c.cc.Invoke(ctx, UserRoleAssignmentService_IsAssigned_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleAssignmentServiceClient) GetIdByRoleAssignmentId(ctx context.Context, in *GetIdByRoleAssignmentIdRequest, opts ...grpc.CallOption) (*GetIdByRoleAssignmentIdResponse, error) {
	out := new(GetIdByRoleAssignmentIdResponse)
	err := c.cc.Invoke(ctx, UserRoleAssignmentService_GetIdByRoleAssignmentId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleAssignmentServiceClient) GetStatusById(ctx context.Context, in *GetStatusByIdRequest, opts ...grpc.CallOption) (*GetStatusByIdResponse, error) {
	out := new(GetStatusByIdResponse)
	err := c.cc.Invoke(ctx, UserRoleAssignmentService_GetStatusById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleAssignmentServiceClient) GetStatusByRoleAssignmentId(ctx context.Context, in *GetStatusByRoleAssignmentIdRequest, opts ...grpc.CallOption) (*GetStatusByRoleAssignmentIdResponse, error) {
	out := new(GetStatusByRoleAssignmentIdResponse)
	err := c.cc.Invoke(ctx, UserRoleAssignmentService_GetStatusByRoleAssignmentId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleAssignmentServiceClient) GetUserRoleIdsByUserId(ctx context.Context, in *GetUserRoleIdsByUserIdRequest, opts ...grpc.CallOption) (*GetUserRoleIdsByUserIdResponse, error) {
	out := new(GetUserRoleIdsByUserIdResponse)
	err := c.cc.Invoke(ctx, UserRoleAssignmentService_GetUserRoleIdsByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRoleAssignmentServiceServer is the server API for UserRoleAssignmentService service.
// All implementations must embed UnimplementedUserRoleAssignmentServiceServer
// for forward compatibility
type UserRoleAssignmentServiceServer interface {
	// Gets a user's role assignment by the specified user's role assignment ID.
	GetById(context.Context, *GetByIdRequest) (*GetByIdResponse, error)
	// Gets a user's role assignment by the specified role assignment ID.
	GetByRoleAssignmentId(context.Context, *GetByRoleAssignmentIdRequest) (*GetByRoleAssignmentIdResponse, error)
	// Gets all user's role assignments by the specified user ID.
	GetAllByUserId(context.Context, *GetAllByUserIdRequest) (*GetAllByUserIdResponse, error)
	// Returns true if the user's role assignment exists.
	Exists(context.Context, *ExistsRequest) (*ExistsResponse, error)
	// Returns true if the role is assigned to the user.
	IsAssigned(context.Context, *IsAssignedRequest) (*IsAssignedResponse, error)
	// Gets the user's role assignment ID by the specified role assignment ID.
	GetIdByRoleAssignmentId(context.Context, *GetIdByRoleAssignmentIdRequest) (*GetIdByRoleAssignmentIdResponse, error)
	// Gets a user's role assignment status by the specified user's role assignment ID.
	GetStatusById(context.Context, *GetStatusByIdRequest) (*GetStatusByIdResponse, error)
	// Gets a user's role assignment status by the specified role assignment ID.
	GetStatusByRoleAssignmentId(context.Context, *GetStatusByRoleAssignmentIdRequest) (*GetStatusByRoleAssignmentIdResponse, error)
	// Gets the IDs of the roles assigned to the user by the specified user ID.
	// If the role filter is empty, then all assigned roles are returned, otherwise only the roles
	// specified in the filter, if any, are returned.
	GetUserRoleIdsByUserId(context.Context, *GetUserRoleIdsByUserIdRequest) (*GetUserRoleIdsByUserIdResponse, error)
	mustEmbedUnimplementedUserRoleAssignmentServiceServer()
}

// UnimplementedUserRoleAssignmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserRoleAssignmentServiceServer struct {
}

func (UnimplementedUserRoleAssignmentServiceServer) GetById(context.Context, *GetByIdRequest) (*GetByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedUserRoleAssignmentServiceServer) GetByRoleAssignmentId(context.Context, *GetByRoleAssignmentIdRequest) (*GetByRoleAssignmentIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByRoleAssignmentId not implemented")
}
func (UnimplementedUserRoleAssignmentServiceServer) GetAllByUserId(context.Context, *GetAllByUserIdRequest) (*GetAllByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllByUserId not implemented")
}
func (UnimplementedUserRoleAssignmentServiceServer) Exists(context.Context, *ExistsRequest) (*ExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedUserRoleAssignmentServiceServer) IsAssigned(context.Context, *IsAssignedRequest) (*IsAssignedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAssigned not implemented")
}
func (UnimplementedUserRoleAssignmentServiceServer) GetIdByRoleAssignmentId(context.Context, *GetIdByRoleAssignmentIdRequest) (*GetIdByRoleAssignmentIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdByRoleAssignmentId not implemented")
}
func (UnimplementedUserRoleAssignmentServiceServer) GetStatusById(context.Context, *GetStatusByIdRequest) (*GetStatusByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatusById not implemented")
}
func (UnimplementedUserRoleAssignmentServiceServer) GetStatusByRoleAssignmentId(context.Context, *GetStatusByRoleAssignmentIdRequest) (*GetStatusByRoleAssignmentIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatusByRoleAssignmentId not implemented")
}
func (UnimplementedUserRoleAssignmentServiceServer) GetUserRoleIdsByUserId(context.Context, *GetUserRoleIdsByUserIdRequest) (*GetUserRoleIdsByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRoleIdsByUserId not implemented")
}
func (UnimplementedUserRoleAssignmentServiceServer) mustEmbedUnimplementedUserRoleAssignmentServiceServer() {
}

// UnsafeUserRoleAssignmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRoleAssignmentServiceServer will
// result in compilation errors.
type UnsafeUserRoleAssignmentServiceServer interface {
	mustEmbedUnimplementedUserRoleAssignmentServiceServer()
}

func RegisterUserRoleAssignmentServiceServer(s grpc.ServiceRegistrar, srv UserRoleAssignmentServiceServer) {
	s.RegisterService(&UserRoleAssignmentService_ServiceDesc, srv)
}

func _UserRoleAssignmentService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleAssignmentServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleAssignmentService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleAssignmentServiceServer).GetById(ctx, req.(*GetByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleAssignmentService_GetByRoleAssignmentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByRoleAssignmentIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleAssignmentServiceServer).GetByRoleAssignmentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleAssignmentService_GetByRoleAssignmentId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleAssignmentServiceServer).GetByRoleAssignmentId(ctx, req.(*GetByRoleAssignmentIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleAssignmentService_GetAllByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleAssignmentServiceServer).GetAllByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleAssignmentService_GetAllByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleAssignmentServiceServer).GetAllByUserId(ctx, req.(*GetAllByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleAssignmentService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleAssignmentServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleAssignmentService_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleAssignmentServiceServer).Exists(ctx, req.(*ExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleAssignmentService_IsAssigned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAssignedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleAssignmentServiceServer).IsAssigned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleAssignmentService_IsAssigned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleAssignmentServiceServer).IsAssigned(ctx, req.(*IsAssignedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleAssignmentService_GetIdByRoleAssignmentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdByRoleAssignmentIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleAssignmentServiceServer).GetIdByRoleAssignmentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleAssignmentService_GetIdByRoleAssignmentId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleAssignmentServiceServer).GetIdByRoleAssignmentId(ctx, req.(*GetIdByRoleAssignmentIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleAssignmentService_GetStatusById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleAssignmentServiceServer).GetStatusById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleAssignmentService_GetStatusById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleAssignmentServiceServer).GetStatusById(ctx, req.(*GetStatusByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleAssignmentService_GetStatusByRoleAssignmentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusByRoleAssignmentIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleAssignmentServiceServer).GetStatusByRoleAssignmentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleAssignmentService_GetStatusByRoleAssignmentId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleAssignmentServiceServer).GetStatusByRoleAssignmentId(ctx, req.(*GetStatusByRoleAssignmentIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleAssignmentService_GetUserRoleIdsByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRoleIdsByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleAssignmentServiceServer).GetUserRoleIdsByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleAssignmentService_GetUserRoleIdsByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleAssignmentServiceServer).GetUserRoleIdsByUserId(ctx, req.(*GetUserRoleIdsByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRoleAssignmentService_ServiceDesc is the grpc.ServiceDesc for UserRoleAssignmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRoleAssignmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "personalwebsite.identity.roles.userroleassignments.UserRoleAssignmentService",
	HandlerType: (*UserRoleAssignmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _UserRoleAssignmentService_GetById_Handler,
		},
		{
			MethodName: "GetByRoleAssignmentId",
			Handler:    _UserRoleAssignmentService_GetByRoleAssignmentId_Handler,
		},
		{
			MethodName: "GetAllByUserId",
			Handler:    _UserRoleAssignmentService_GetAllByUserId_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _UserRoleAssignmentService_Exists_Handler,
		},
		{
			MethodName: "IsAssigned",
			Handler:    _UserRoleAssignmentService_IsAssigned_Handler,
		},
		{
			MethodName: "GetIdByRoleAssignmentId",
			Handler:    _UserRoleAssignmentService_GetIdByRoleAssignmentId_Handler,
		},
		{
			MethodName: "GetStatusById",
			Handler:    _UserRoleAssignmentService_GetStatusById_Handler,
		},
		{
			MethodName: "GetStatusByRoleAssignmentId",
			Handler:    _UserRoleAssignmentService_GetStatusByRoleAssignmentId_Handler,
		},
		{
			MethodName: "GetUserRoleIdsByUserId",
			Handler:    _UserRoleAssignmentService_GetUserRoleIdsByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis/identity/roles/userroleassignments/user_role_assignment_service.proto",
}
