// Copyright 2023 Alexey Lavrenchenko. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: data/actions/action.proto

package actions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	app "personal-website-v2/go-data/app"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The action category.
type ActionCategoryEnum_ActionCategory int32

const (
	// Unspecified. Do not use.
	ActionCategoryEnum_UNSPECIFIED ActionCategoryEnum_ActionCategory = 0
	// Common actions.
	ActionCategoryEnum_COMMON ActionCategoryEnum_ActionCategory = 1
	ActionCategoryEnum_HTTP   ActionCategoryEnum_ActionCategory = 2
	ActionCategoryEnum_GRPC   ActionCategoryEnum_ActionCategory = 3
)

// Enum value maps for ActionCategoryEnum_ActionCategory.
var (
	ActionCategoryEnum_ActionCategory_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "COMMON",
		2: "HTTP",
		3: "GRPC",
	}
	ActionCategoryEnum_ActionCategory_value = map[string]int32{
		"UNSPECIFIED": 0,
		"COMMON":      1,
		"HTTP":        2,
		"GRPC":        3,
	}
)

func (x ActionCategoryEnum_ActionCategory) Enum() *ActionCategoryEnum_ActionCategory {
	p := new(ActionCategoryEnum_ActionCategory)
	*p = x
	return p
}

func (x ActionCategoryEnum_ActionCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionCategoryEnum_ActionCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_data_actions_action_proto_enumTypes[0].Descriptor()
}

func (ActionCategoryEnum_ActionCategory) Type() protoreflect.EnumType {
	return &file_data_actions_action_proto_enumTypes[0]
}

func (x ActionCategoryEnum_ActionCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionCategoryEnum_ActionCategory.Descriptor instead.
func (ActionCategoryEnum_ActionCategory) EnumDescriptor() ([]byte, []int) {
	return file_data_actions_action_proto_rawDescGZIP(), []int{1, 0}
}

// The action status.
type ActionStatusEnum_ActionStatus int32

const (
	// Unspecified. Do not use.
	ActionStatusEnum_UNSPECIFIED ActionStatusEnum_ActionStatus = 0
	ActionStatusEnum_NEW         ActionStatusEnum_ActionStatus = 1
	ActionStatusEnum_IN_PROGRESS ActionStatusEnum_ActionStatus = 2
	ActionStatusEnum_SUCCESS     ActionStatusEnum_ActionStatus = 3
	ActionStatusEnum_FAILURE     ActionStatusEnum_ActionStatus = 4
)

// Enum value maps for ActionStatusEnum_ActionStatus.
var (
	ActionStatusEnum_ActionStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NEW",
		2: "IN_PROGRESS",
		3: "SUCCESS",
		4: "FAILURE",
	}
	ActionStatusEnum_ActionStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"NEW":         1,
		"IN_PROGRESS": 2,
		"SUCCESS":     3,
		"FAILURE":     4,
	}
)

func (x ActionStatusEnum_ActionStatus) Enum() *ActionStatusEnum_ActionStatus {
	p := new(ActionStatusEnum_ActionStatus)
	*p = x
	return p
}

func (x ActionStatusEnum_ActionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionStatusEnum_ActionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_data_actions_action_proto_enumTypes[1].Descriptor()
}

func (ActionStatusEnum_ActionStatus) Type() protoreflect.EnumType {
	return &file_data_actions_action_proto_enumTypes[1]
}

func (x ActionStatusEnum_ActionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionStatusEnum_ActionStatus.Descriptor instead.
func (ActionStatusEnum_ActionStatus) EnumDescriptor() ([]byte, []int) {
	return file_data_actions_action_proto_rawDescGZIP(), []int{2, 0}
}

// The action.
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique ID to identify the action.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The app info.
	App *app.AppInfo `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	// The app session ID.
	AppSessionId uint64 `protobuf:"varint,3,opt,name=app_session_id,json=appSessionId,proto3" json:"app_session_id,omitempty"`
	// The transaction ID.
	TranId string `protobuf:"bytes,4,opt,name=tran_id,json=tranId,proto3" json:"tran_id,omitempty"`
	// The action type.
	Type uint64 `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	// The action category.
	Category ActionCategoryEnum_ActionCategory `protobuf:"varint,6,opt,name=category,proto3,enum=personalwebsite.actions.ActionCategoryEnum_ActionCategory" json:"category,omitempty"`
	// The action group.
	Group uint64 `protobuf:"varint,7,opt,name=group,proto3" json:"group,omitempty"`
	// Optional. The parent action ID.
	ParentActionId *string `protobuf:"bytes,8,opt,name=parent_action_id,json=parentActionId,proto3,oneof" json:"parent_action_id,omitempty"`
	IsBackground   bool    `protobuf:"varint,9,opt,name=is_background,json=isBackground,proto3" json:"is_background,omitempty"`
	// The date and time (in microseconds) at which the action was created.
	CreatedAt int64 `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The status of the action can be New(1), InProgress(2), Success(3), or Failure(4).
	Status ActionStatusEnum_ActionStatus `protobuf:"varint,11,opt,name=status,proto3,enum=personalwebsite.actions.ActionStatusEnum_ActionStatus" json:"status,omitempty"`
	// The date and time (in microseconds) at which the action was started.
	StartTime int64 `protobuf:"varint,12,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Optional. The date and time (in microseconds) at which the action was ended.
	EndTime *int64 `protobuf:"varint,13,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	// Optional. The elapsed time, in microseconds.
	ElapsedTimeUs *int64 `protobuf:"varint,14,opt,name=elapsed_time_us,json=elapsedTimeUs,proto3,oneof" json:"elapsed_time_us,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_actions_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_data_actions_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_data_actions_action_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action) GetApp() *app.AppInfo {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *Action) GetAppSessionId() uint64 {
	if x != nil {
		return x.AppSessionId
	}
	return 0
}

func (x *Action) GetTranId() string {
	if x != nil {
		return x.TranId
	}
	return ""
}

func (x *Action) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Action) GetCategory() ActionCategoryEnum_ActionCategory {
	if x != nil {
		return x.Category
	}
	return ActionCategoryEnum_UNSPECIFIED
}

func (x *Action) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Action) GetParentActionId() string {
	if x != nil && x.ParentActionId != nil {
		return *x.ParentActionId
	}
	return ""
}

func (x *Action) GetIsBackground() bool {
	if x != nil {
		return x.IsBackground
	}
	return false
}

func (x *Action) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Action) GetStatus() ActionStatusEnum_ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatusEnum_UNSPECIFIED
}

func (x *Action) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Action) GetEndTime() int64 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

func (x *Action) GetElapsedTimeUs() int64 {
	if x != nil && x.ElapsedTimeUs != nil {
		return *x.ElapsedTimeUs
	}
	return 0
}

// Container for enum describing the action category.
type ActionCategoryEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ActionCategoryEnum) Reset() {
	*x = ActionCategoryEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_actions_action_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionCategoryEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCategoryEnum) ProtoMessage() {}

func (x *ActionCategoryEnum) ProtoReflect() protoreflect.Message {
	mi := &file_data_actions_action_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCategoryEnum.ProtoReflect.Descriptor instead.
func (*ActionCategoryEnum) Descriptor() ([]byte, []int) {
	return file_data_actions_action_proto_rawDescGZIP(), []int{1}
}

// Container for enum describing the action status.
type ActionStatusEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ActionStatusEnum) Reset() {
	*x = ActionStatusEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_actions_action_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionStatusEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStatusEnum) ProtoMessage() {}

func (x *ActionStatusEnum) ProtoReflect() protoreflect.Message {
	mi := &file_data_actions_action_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStatusEnum.ProtoReflect.Descriptor instead.
func (*ActionStatusEnum) Descriptor() ([]byte, []int) {
	return file_data_actions_action_proto_rawDescGZIP(), []int{2}
}

var File_data_actions_action_proto protoreflect.FileDescriptor

var file_data_actions_action_proto_rawDesc = []byte{
	0x0a, 0x19, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x70, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x17, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x61,
	0x70, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xee, 0x04,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c,
	0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x24, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x5f,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x61, 0x70, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x72, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x72, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x56, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x2e,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x2d, 0x0a, 0x10, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x62,
	0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0c, 0x69, 0x73, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x4e, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x36, 0x2e, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x0f, 0x65,
	0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x03, 0x48, 0x02, 0x52, 0x0d, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x55, 0x73, 0x88, 0x01, 0x01, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x65,
	0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x22, 0x57,
	0x0a, 0x12, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x45, 0x6e, 0x75, 0x6d, 0x22, 0x41, 0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x4d, 0x4d, 0x4f,
	0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x47, 0x52, 0x50, 0x43, 0x10, 0x03, 0x22, 0x67, 0x0a, 0x10, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x53, 0x0a, 0x0c, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x4e, 0x45, 0x57, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47,
	0x52, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x04,
	0x42, 0x2d, 0x5a, 0x2b, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x2d, 0x77, 0x65, 0x62,
	0x73, 0x69, 0x74, 0x65, 0x2d, 0x76, 0x32, 0x2f, 0x67, 0x6f, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2f,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_actions_action_proto_rawDescOnce sync.Once
	file_data_actions_action_proto_rawDescData = file_data_actions_action_proto_rawDesc
)

func file_data_actions_action_proto_rawDescGZIP() []byte {
	file_data_actions_action_proto_rawDescOnce.Do(func() {
		file_data_actions_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_actions_action_proto_rawDescData)
	})
	return file_data_actions_action_proto_rawDescData
}

var file_data_actions_action_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_data_actions_action_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_data_actions_action_proto_goTypes = []interface{}{
	(ActionCategoryEnum_ActionCategory)(0), // 0: personalwebsite.actions.ActionCategoryEnum.ActionCategory
	(ActionStatusEnum_ActionStatus)(0),     // 1: personalwebsite.actions.ActionStatusEnum.ActionStatus
	(*Action)(nil),                         // 2: personalwebsite.actions.Action
	(*ActionCategoryEnum)(nil),             // 3: personalwebsite.actions.ActionCategoryEnum
	(*ActionStatusEnum)(nil),               // 4: personalwebsite.actions.ActionStatusEnum
	(*app.AppInfo)(nil),                    // 5: personalwebsite.app.AppInfo
}
var file_data_actions_action_proto_depIdxs = []int32{
	5, // 0: personalwebsite.actions.Action.app:type_name -> personalwebsite.app.AppInfo
	0, // 1: personalwebsite.actions.Action.category:type_name -> personalwebsite.actions.ActionCategoryEnum.ActionCategory
	1, // 2: personalwebsite.actions.Action.status:type_name -> personalwebsite.actions.ActionStatusEnum.ActionStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_data_actions_action_proto_init() }
func file_data_actions_action_proto_init() {
	if File_data_actions_action_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_actions_action_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_actions_action_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionCategoryEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_actions_action_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionStatusEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_data_actions_action_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_actions_action_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_actions_action_proto_goTypes,
		DependencyIndexes: file_data_actions_action_proto_depIdxs,
		EnumInfos:         file_data_actions_action_proto_enumTypes,
		MessageInfos:      file_data_actions_action_proto_msgTypes,
	}.Build()
	File_data_actions_action_proto = out.File
	file_data_actions_action_proto_rawDesc = nil
	file_data_actions_action_proto_goTypes = nil
	file_data_actions_action_proto_depIdxs = nil
}
