// Copyright 2023 Alexey Lavrenchenko. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: data/actions/operation.proto

package actions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	app "personal-website-v2/go-data/app"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The operation category.
type OperationCategoryEnum_OperationCategory int32

const (
	// Unspecified. Do not use.
	OperationCategoryEnum_UNSPECIFIED OperationCategoryEnum_OperationCategory = 0
	// Common operations.
	OperationCategoryEnum_COMMON OperationCategoryEnum_OperationCategory = 1
	// Identification, authentication, authorization user/client.
	OperationCategoryEnum_IDENTITY OperationCategoryEnum_OperationCategory = 2
	// For example, MySQL, PostgreSQL.
	OperationCategoryEnum_DATABASE OperationCategoryEnum_OperationCategory = 3
	// For example, Redis.
	OperationCategoryEnum_CACHE_STORAGE OperationCategoryEnum_OperationCategory = 4
)

// Enum value maps for OperationCategoryEnum_OperationCategory.
var (
	OperationCategoryEnum_OperationCategory_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "COMMON",
		2: "IDENTITY",
		3: "DATABASE",
		4: "CACHE_STORAGE",
	}
	OperationCategoryEnum_OperationCategory_value = map[string]int32{
		"UNSPECIFIED":   0,
		"COMMON":        1,
		"IDENTITY":      2,
		"DATABASE":      3,
		"CACHE_STORAGE": 4,
	}
)

func (x OperationCategoryEnum_OperationCategory) Enum() *OperationCategoryEnum_OperationCategory {
	p := new(OperationCategoryEnum_OperationCategory)
	*p = x
	return p
}

func (x OperationCategoryEnum_OperationCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationCategoryEnum_OperationCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_data_actions_operation_proto_enumTypes[0].Descriptor()
}

func (OperationCategoryEnum_OperationCategory) Type() protoreflect.EnumType {
	return &file_data_actions_operation_proto_enumTypes[0]
}

func (x OperationCategoryEnum_OperationCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationCategoryEnum_OperationCategory.Descriptor instead.
func (OperationCategoryEnum_OperationCategory) EnumDescriptor() ([]byte, []int) {
	return file_data_actions_operation_proto_rawDescGZIP(), []int{1, 0}
}

// The operation status.
type OperationStatusEnum_OperationStatus int32

const (
	// Unspecified. Do not use.
	OperationStatusEnum_UNSPECIFIED OperationStatusEnum_OperationStatus = 0
	OperationStatusEnum_NEW         OperationStatusEnum_OperationStatus = 1
	OperationStatusEnum_IN_PROGRESS OperationStatusEnum_OperationStatus = 2
	OperationStatusEnum_SUCCESS     OperationStatusEnum_OperationStatus = 3
	OperationStatusEnum_FAILURE     OperationStatusEnum_OperationStatus = 4
)

// Enum value maps for OperationStatusEnum_OperationStatus.
var (
	OperationStatusEnum_OperationStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NEW",
		2: "IN_PROGRESS",
		3: "SUCCESS",
		4: "FAILURE",
	}
	OperationStatusEnum_OperationStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"NEW":         1,
		"IN_PROGRESS": 2,
		"SUCCESS":     3,
		"FAILURE":     4,
	}
)

func (x OperationStatusEnum_OperationStatus) Enum() *OperationStatusEnum_OperationStatus {
	p := new(OperationStatusEnum_OperationStatus)
	*p = x
	return p
}

func (x OperationStatusEnum_OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatusEnum_OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_data_actions_operation_proto_enumTypes[1].Descriptor()
}

func (OperationStatusEnum_OperationStatus) Type() protoreflect.EnumType {
	return &file_data_actions_operation_proto_enumTypes[1]
}

func (x OperationStatusEnum_OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatusEnum_OperationStatus.Descriptor instead.
func (OperationStatusEnum_OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_data_actions_operation_proto_rawDescGZIP(), []int{2, 0}
}

// The operation.
type Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique ID to identify the operation.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The app info.
	App *app.AppInfo `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	// The app session ID.
	AppSessionId uint64 `protobuf:"varint,3,opt,name=app_session_id,json=appSessionId,proto3" json:"app_session_id,omitempty"`
	// The transaction ID.
	TranId string `protobuf:"bytes,4,opt,name=tran_id,json=tranId,proto3" json:"tran_id,omitempty"`
	// The action ID.
	ActionId string `protobuf:"bytes,5,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	// The operation type.
	Type uint64 `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	// The operation category.
	Category OperationCategoryEnum_OperationCategory `protobuf:"varint,7,opt,name=category,proto3,enum=personalwebsite.actions.OperationCategoryEnum_OperationCategory" json:"category,omitempty"`
	// The operation group.
	Group uint64 `protobuf:"varint,8,opt,name=group,proto3" json:"group,omitempty"`
	// Optional. The parent operation ID.
	ParentOperationId *string `protobuf:"bytes,9,opt,name=parent_operation_id,json=parentOperationId,proto3,oneof" json:"parent_operation_id,omitempty"`
	// Optional. The JSON-encoded params.
	Params *string `protobuf:"bytes,10,opt,name=params,proto3,oneof" json:"params,omitempty"`
	// The date and time (in microseconds) at which the operation was created.
	CreatedAt int64 `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The status of the operation can be New(1), InProgress(2), Success(3), or Failure(4).
	Status OperationStatusEnum_OperationStatus `protobuf:"varint,12,opt,name=status,proto3,enum=personalwebsite.actions.OperationStatusEnum_OperationStatus" json:"status,omitempty"`
	// The date and time (in microseconds) at which the operation was started.
	StartTime int64 `protobuf:"varint,13,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Optional. The date and time (in microseconds) at which the operation was ended.
	EndTime *int64 `protobuf:"varint,14,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	// Optional. The elapsed time, in microseconds.
	ElapsedTimeUs *int64 `protobuf:"varint,15,opt,name=elapsed_time_us,json=elapsedTimeUs,proto3,oneof" json:"elapsed_time_us,omitempty"`
}

func (x *Operation) Reset() {
	*x = Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_actions_operation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_data_actions_operation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_data_actions_operation_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operation) GetApp() *app.AppInfo {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *Operation) GetAppSessionId() uint64 {
	if x != nil {
		return x.AppSessionId
	}
	return 0
}

func (x *Operation) GetTranId() string {
	if x != nil {
		return x.TranId
	}
	return ""
}

func (x *Operation) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *Operation) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Operation) GetCategory() OperationCategoryEnum_OperationCategory {
	if x != nil {
		return x.Category
	}
	return OperationCategoryEnum_UNSPECIFIED
}

func (x *Operation) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Operation) GetParentOperationId() string {
	if x != nil && x.ParentOperationId != nil {
		return *x.ParentOperationId
	}
	return ""
}

func (x *Operation) GetParams() string {
	if x != nil && x.Params != nil {
		return *x.Params
	}
	return ""
}

func (x *Operation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Operation) GetStatus() OperationStatusEnum_OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatusEnum_UNSPECIFIED
}

func (x *Operation) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Operation) GetEndTime() int64 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

func (x *Operation) GetElapsedTimeUs() int64 {
	if x != nil && x.ElapsedTimeUs != nil {
		return *x.ElapsedTimeUs
	}
	return 0
}

// Container for enum describing the operation category.
type OperationCategoryEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OperationCategoryEnum) Reset() {
	*x = OperationCategoryEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_actions_operation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationCategoryEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationCategoryEnum) ProtoMessage() {}

func (x *OperationCategoryEnum) ProtoReflect() protoreflect.Message {
	mi := &file_data_actions_operation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationCategoryEnum.ProtoReflect.Descriptor instead.
func (*OperationCategoryEnum) Descriptor() ([]byte, []int) {
	return file_data_actions_operation_proto_rawDescGZIP(), []int{1}
}

// Container for enum describing the operation status.
type OperationStatusEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OperationStatusEnum) Reset() {
	*x = OperationStatusEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_actions_operation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationStatusEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStatusEnum) ProtoMessage() {}

func (x *OperationStatusEnum) ProtoReflect() protoreflect.Message {
	mi := &file_data_actions_operation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStatusEnum.ProtoReflect.Descriptor instead.
func (*OperationStatusEnum) Descriptor() ([]byte, []int) {
	return file_data_actions_operation_proto_rawDescGZIP(), []int{2}
}

var File_data_actions_operation_proto protoreflect.FileDescriptor

var file_data_actions_operation_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x2e,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x17, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x70,
	0x70, 0x2f, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xa6, 0x05, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e,
	0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x24,
	0x0a, 0x0e, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x61, 0x70, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x72, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x5c,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x40, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x77, 0x65, 0x62, 0x73, 0x69,
	0x74, 0x65, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x75, 0x6d,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x33, 0x0a, 0x13, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x11, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x54, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x3c, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x77, 0x65,
	0x62, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75,
	0x6d, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x48, 0x02, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x0f, 0x65, 0x6c, 0x61, 0x70,
	0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x03, 0x52, 0x0d, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x55, 0x73, 0x88, 0x01, 0x01, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x6e, 0x64,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x22, 0x78, 0x0a, 0x15, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x45, 0x6e,
	0x75, 0x6d, 0x22, 0x5f, 0x0a, 0x11, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x4d, 0x4d,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59,
	0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x41, 0x54, 0x41, 0x42, 0x41, 0x53, 0x45, 0x10, 0x03,
	0x12, 0x11, 0x0a, 0x0d, 0x43, 0x41, 0x43, 0x48, 0x45, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47,
	0x45, 0x10, 0x04, 0x22, 0x6d, 0x0a, 0x13, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x56, 0x0a, 0x0f, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a,
	0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x5f, 0x50, 0x52,
	0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45,
	0x10, 0x04, 0x42, 0x2d, 0x5a, 0x2b, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x2d, 0x77,
	0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x2d, 0x76, 0x32, 0x2f, 0x67, 0x6f, 0x2d, 0x64, 0x61, 0x74,
	0x61, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_actions_operation_proto_rawDescOnce sync.Once
	file_data_actions_operation_proto_rawDescData = file_data_actions_operation_proto_rawDesc
)

func file_data_actions_operation_proto_rawDescGZIP() []byte {
	file_data_actions_operation_proto_rawDescOnce.Do(func() {
		file_data_actions_operation_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_actions_operation_proto_rawDescData)
	})
	return file_data_actions_operation_proto_rawDescData
}

var file_data_actions_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_data_actions_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_data_actions_operation_proto_goTypes = []interface{}{
	(OperationCategoryEnum_OperationCategory)(0), // 0: personalwebsite.actions.OperationCategoryEnum.OperationCategory
	(OperationStatusEnum_OperationStatus)(0),     // 1: personalwebsite.actions.OperationStatusEnum.OperationStatus
	(*Operation)(nil),                            // 2: personalwebsite.actions.Operation
	(*OperationCategoryEnum)(nil),                // 3: personalwebsite.actions.OperationCategoryEnum
	(*OperationStatusEnum)(nil),                  // 4: personalwebsite.actions.OperationStatusEnum
	(*app.AppInfo)(nil),                          // 5: personalwebsite.app.AppInfo
}
var file_data_actions_operation_proto_depIdxs = []int32{
	5, // 0: personalwebsite.actions.Operation.app:type_name -> personalwebsite.app.AppInfo
	0, // 1: personalwebsite.actions.Operation.category:type_name -> personalwebsite.actions.OperationCategoryEnum.OperationCategory
	1, // 2: personalwebsite.actions.Operation.status:type_name -> personalwebsite.actions.OperationStatusEnum.OperationStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_data_actions_operation_proto_init() }
func file_data_actions_operation_proto_init() {
	if File_data_actions_operation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_actions_operation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_actions_operation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationCategoryEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_actions_operation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationStatusEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_data_actions_operation_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_actions_operation_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_actions_operation_proto_goTypes,
		DependencyIndexes: file_data_actions_operation_proto_depIdxs,
		EnumInfos:         file_data_actions_operation_proto_enumTypes,
		MessageInfos:      file_data_actions_operation_proto_msgTypes,
	}.Build()
	File_data_actions_operation_proto = out.File
	file_data_actions_operation_proto_rawDesc = nil
	file_data_actions_operation_proto_goTypes = nil
	file_data_actions_operation_proto_depIdxs = nil
}
